### ISSUE TITLE
Word60.model文件百度网盘链接失效,可否重新提供一份下载地址，万分感谢！

### ISSUE THREAD

**Issue by mucahaha** [LuJunru/My_QA_Robot#2]
Word60.model文件百度网盘链接失效,可否重新提供一份下载地址，谢谢作者的热心分享！！

**Comment by LuJunru** [comment]
不好意思啊，这个链接不是我分享出来的。你可以参考一下这个：https://github.com/Embedding/Chinese-Word-Vectors
